# Generated by Django 5.1 on 2026-03-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_shippingmethod_order_shipping_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_since', models.DateTimeField(auto_now_add=True)),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockpile', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockpiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockpileFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_accrued', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('stockpile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_logs', to='stockpile.stockpile')),
            ],
        ),
    ]
