# Generated by Django 5.1 on 2026-03-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text="e.g., '7', '18 inch'", max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text="e.g., 'Rose Gold'", max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.jewelleryimage')),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogue.jewellery')),
            ],
            options={
                'unique_together': {('jewellery', 'size', 'color')},
            },
        ),
    ]
